import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SessionWrapper from "./context/SessionWrapper";
import { ListProvider } from "./context/ListContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Task It",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} min-h-screen w-full ${geistMono.variable} antialiased`}
      >
        <div className="w-full md:bg-[url('/extras/dektop-background.png')] bg-[url('/extras/mobile-background.png')] bg-no-repeat bg-fixed bg-cover min-h-screen">
          <ListProvider>
            <SessionWrapper>{children}</SessionWrapper>
          </ListProvider>
          <ToastContainer position="top-right" />
        </div>
      </body>
    </html>
  );
}
